### ISSUE TITLE
Including model types in serialized responses

### ISSUE THREAD

**Issue by daxaxelrod** [Ian-Foote/rest-framework-generic-relations#58]
Hi, Thanks for this lib! I'd like my frontend to have a bit more context as to what type of component to render and would like to include the model type when serializing.

To accomplish this, i've modified the to_representaion method and am using a derived class. 

```python
class GenericRelatedFieldWithType(GenericRelatedField):
    def to_representation(self, instance):
        data = super(GenericRelatedFieldWithType, self).to_representation(instance)
        data.update({"type": self.Meta.model.__name__})
        return data
```

Is this how you would do the same and would it be something that this lib would accept a PR for (an additional include_type=True|False)? Thanks

**Comment by craigds** [comment]
Thanks for the suggestion!

It's not something I'd want to include in this library, for two reasons:

* different users will have quite different ideas about how to render the type field. Some possibilities:
  - model class name
  - `appname.modelname`
  - lowercased model name
  - a nested serializer for a ContentType instance
  - nothing at all

* it's easy enough for callers to define this behaviour in the child serializers directly, rather than extending the GenericRelatedField itself. If the child serializers share a common base mixin it can be defined in one place there.

Thanks
